###
POST http://localhost:8080/api/sellorder/majorist
Content-Type: application/json

{
  "yearOfHarvest": 2023,
  "productId": "NARANJA",
  "quantity": 300,
  "marketRateDay": "2023-12-05",
  "distance": 180
}

###
