
POST http://{{serveraddress}}/api/producer/limit/2023/5
###
POST http://{{serveraddress}}/api/product/
Content-Type: application/json

{
  "productId": "NARANJA",
  "productName": "naranja",
  "productionPerHectare": 100,
  "initialPricePerKilogram": "2.4",
  "productType": "PERISHABLE"
}

###
POST http://{{serveraddress}}/api/product/
Content-Type: application/json

{
  "productId": "LIMON",
  "productName": "limon",
  "productionPerHectare": 200,
  "initialPricePerKilogram": "3.5",
  "productType": "NOT_PERISHABLE"
}
###
POST http://{{serveraddress}}/api/product/pricePerKilogram
Content-Type: application/json

{
  "productId": "NARANJA",
  "pricePerKilogram": "3.0",
  "day": "2023-10-13"
}
###
POST http://{{serveraddress}}/api/producer
Content-Type: application/json

{
  "producerId": "PEPITO",
  "producerName": "pepito"
}
###
POST http://{{serveraddress}}/api/producer
Content-Type: application/json

{
  "producerId": "JUANITO",
  "producerName": "juanito"
}
###
POST http://{{serveraddress}}/api/producer
Content-Type: application/json

{
  "producerId": "ROCKEFELLER",
  "producerName": "rockefeller"
}
###
POST http://{{serveraddress}}/api/producer/fields
Content-Type: application/json

{
  "producerId": "PEPITO",
  "year": 2023,
  "fields": [
    {
      "productId": "NARANJA",
      "hectares": 2
    },
    {
      "productId": "LIMON",
      "hectares": 2.5
    }
  ]
}

<> 2023-05-13T235934.500.json
###
POST http://{{serveraddress}}/api/producer/fields
Content-Type: application/json

{
  "producerId": "JUANITO",
  "year": 2023,
  "fields": [
    {
      "productId": "NARANJA",
      "hectares": 1
    },
    {
      "productId": "LIMON",
      "hectares": 0.5
    }
  ]
}
###
POST http://{{serveraddress}}/api/producer/fields
Content-Type: application/json

{
  "producerId": "ROCKEFELLER",
  "year": 2023,
  "fields": [
    {
      "productId": "NARANJA",
      "hectares": 20
    },
    {
      "productId": "LIMON",
      "hectares": 30
    }
  ]
}

<> 2023-05-14T001910.500.json
<> 2023-05-14T000056.500.json
<> 2023-05-13T235959.500.json
<> 2023-05-13T235746.500.json
###
POST http://{{serveraddress}}/api/buyorder/nonfedered
Content-Type: application/json

{
  "buyOrderUUID": "9edc0689-16f4-4319-ad95-3a8ace029876",
  "year": 2023,
  "producerId": "PEPITO",
  "productId": "NARANJA"
}
###
POST http://{{serveraddress}}/api/buyorder/federed
Content-Type: application/json

{
  "buyOrderUUID": "de0e186e-ceaa-4a9d-b5a4-fb2286048181",
  "year": 2023,
  "producerIds": ["PEPITO", "JUANITO"],
  "productId": "NARANJA"
}

<> 2023-05-14T002430.500.json
<> 2023-05-14T002354.500.json
###
